### ISSUE TITLE
没有必要搞这么多module吧，只是些注解类

### ISSUE THREAD

**Issue by moonljt521** [2017398956/AbcPermission#2]
没有必要搞这么多module吧，只是些注解类

**Comment by 2017398956** [comment]
gradle 3.0.1 对于注解需要 annotationProcessor 并且为了减少生成的 app 中有不必要的类是需要分这么多 module 的，依赖的配置之所以用了 exclude 是因为我没有把这些 module 单独发布在 jitpack 上，这样比较方便控制版本号。
